version: '3'
services:
  # database:
  #   image: mongodb_mongo_db
  web:
    image: heyff12/nodeshop-server
    # depends_on:
    #   - database
    ports:
      - 3003:3003
    links:
      - database
#     networks:
#       - webapp-network
# networks:
#   webapp-network:
#     driver: bridge