version: '3.7'
services:
  database:
    image: mongo
    restart: always
    volumes:
      - ~/data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - webapp-network
  web:
    image: nodeshop
    depends_on:
      - database
    ports:
      - 3003:3003
    networks:
      - webapp-network
networks:
  webapp-network:
    driver: bridge