version: '3.7'
services:
  database:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ~/data/mongodb/db:/data/db
    ports:
      - 27017:27017
    networks:
      - webapp-network
  web:
    image: heyff12/nodeshop-server
    depends_on:
      - database
    ports:
      - 3003:3003
    networks:
      - webapp-network
networks:
  webapp-network:
    driver: bridge