version: '3'
services:
  web:
    image: heyff12/nodeshop-server
    ports:
      - 3003:3003
    container_name: heyff12-nodeshop-server
    networks:
      - default
      - mongo_net
    external_links:
      - mongo_db
networks:
  mongo_net:
    external: true