
name: Ali deploy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: heyff12/nodeshop-server
  VERSION: latest
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.11.3]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      # - run: npm run build --if-present
      # - run: npm test
      #   env:
      #     CI: true

      - name: store server file
        uses: actions/upload-artifact@v2
        with:
          name: server
          path: server

      - name: store package file
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./package*.json

      - name: store dockerfile file
        uses: actions/upload-artifact@v2
        with:
          name: dockerfile
          path: ./Dockerfile

      - name: store deploy file
        uses: actions/upload-artifact@v2
        with:
          name: deploy
          path: deploy

  docker-push-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: server
      - uses: actions/download-artifact@v2
        with:
          name: package
      - uses: actions/download-artifact@v2
        with:
          name: dockerfile
      - name: Build the Docker image
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t $IMAGE_NAME:$VERSION .
          docker push $IMAGE_NAME:$VERSION
  
  docker-run:
    needs: docker-push-image
    runs-on: ubuntu-latest
    env:
      # DOCKER_REG: $IMAGE_NAME:$VERSION
      DOCKER_REG: heyff12/nodeshop-server
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: deploy
      - name: copy shell to remote server
        uses: alinz/ssh-scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          key: ${{ secrets.ACCESS_TOKEN }}
          port: ${{ secrets.REMOTE_PORT }}
          user: ${{ secrets.REMOTE_USER }}
          scp: |
            deploy/* ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:~/deploys/nodeshopServer
      - name: deploy on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.ACCESS_TOKEN }}
          port: ${{ secrets.REMOTE_PORT }}
          command_timeout: 30m
          envs: DOCKER_REG
          script: |
            docker pull $DOCKER_REG
            docker image prune -f
            cd ~/deploys/nodeshopServer
            docker-compose up -d
  
